/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClothingItem {
  'id' : bigint,
  'isPremium' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : { 'accessories' : null } |
    { 'dresses' : null } |
    { 'tops' : null } |
    { 'bottoms' : null },
}
export interface CryptoPayment {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'coin' : string,
  'createdAt' : bigint,
  'txId' : string,
  'user' : Principal,
}
export interface DentalBooking {
  'id' : string,
  'service' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'phone' : string,
}
export interface SalonBooking {
  'id' : bigint,
  'service' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'confirmed' : null },
  'clientName' : string,
  'createdAt' : bigint,
  'appointmentDate' : string,
  'appointmentTime' : string,
  'notes' : string,
  'clientPhone' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateSubscription' : ActorMethod<[], undefined>,
  'addClothingItem' : ActorMethod<[ClothingItem], bigint>,
  'approveCryptoPayment' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deactivateSubscription' : ActorMethod<[], undefined>,
  'deleteClothingItem' : ActorMethod<[bigint], undefined>,
  'deleteDentalBooking' : ActorMethod<[bigint], undefined>,
  'deleteSalonBooking' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClothingCatalog' : ActorMethod<[], Array<ClothingItem>>,
  'getCryptoPendingPayments' : ActorMethod<[], Array<CryptoPayment>>,
  'getDentalBookings' : ActorMethod<[], Array<DentalBooking>>,
  'getItemsByCategory' : ActorMethod<
    [
      { 'accessories' : null } |
        { 'dresses' : null } |
        { 'tops' : null } |
        { 'bottoms' : null },
    ],
    Array<ClothingItem>
  >,
  'getMyPaymentStatus' : ActorMethod<
    [],
    [] | [{ 'pending' : null } | { 'approved' : null } | { 'rejected' : null }]
  >,
  'getSalonBookings' : ActorMethod<[], Array<SalonBooking>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTryOnCountToday' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isSubscribed' : ActorMethod<[], boolean>,
  'recordTryOn' : ActorMethod<[], undefined>,
  'rejectCryptoPayment' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitCryptoPayment' : ActorMethod<[string, string], bigint>,
  'submitDentalBooking' : ActorMethod<
    [
      {
        'service' : string,
        'name' : string,
        'email' : string,
        'message' : string,
        'preferredDate' : string,
        'phone' : string,
      },
    ],
    string
  >,
  'submitSalonBooking' : ActorMethod<
    [
      {
        'service' : string,
        'clientName' : string,
        'appointmentDate' : string,
        'appointmentTime' : string,
        'notes' : string,
        'clientPhone' : string,
      },
    ],
    bigint
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateClothingItem' : ActorMethod<[ClothingItem], undefined>,
  'updateSalonBookingStatus' : ActorMethod<
    [
      bigint,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];