/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClothingItem = IDL.Record({
  'id' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Variant({
    'accessories' : IDL.Null,
    'dresses' : IDL.Null,
    'tops' : IDL.Null,
    'bottoms' : IDL.Null,
  }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CryptoPayment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'coin' : IDL.Text,
  'createdAt' : IDL.Int,
  'txId' : IDL.Text,
  'user' : IDL.Principal,
});
export const DentalBooking = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
});
export const SalonBooking = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'appointmentDate' : IDL.Text,
  'appointmentTime' : IDL.Text,
  'notes' : IDL.Text,
  'clientPhone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateSubscription' : IDL.Func([], [], []),
  'addClothingItem' : IDL.Func([ClothingItem], [IDL.Nat], []),
  'approveCryptoPayment' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateSubscription' : IDL.Func([], [], []),
  'deleteClothingItem' : IDL.Func([IDL.Nat], [], []),
  'deleteDentalBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteSalonBooking' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClothingCatalog' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getCryptoPendingPayments' : IDL.Func(
      [],
      [IDL.Vec(CryptoPayment)],
      ['query'],
    ),
  'getDentalBookings' : IDL.Func([], [IDL.Vec(DentalBooking)], ['query']),
  'getItemsByCategory' : IDL.Func(
      [
        IDL.Variant({
          'accessories' : IDL.Null,
          'dresses' : IDL.Null,
          'tops' : IDL.Null,
          'bottoms' : IDL.Null,
        }),
      ],
      [IDL.Vec(ClothingItem)],
      ['query'],
    ),
  'getMyPaymentStatus' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          })
        ),
      ],
      ['query'],
    ),
  'getSalonBookings' : IDL.Func([], [IDL.Vec(SalonBooking)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTryOnCountToday' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
  'recordTryOn' : IDL.Func([], [], []),
  'rejectCryptoPayment' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitCryptoPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitDentalBooking' : IDL.Func(
      [
        IDL.Record({
          'service' : IDL.Text,
          'name' : IDL.Text,
          'email' : IDL.Text,
          'message' : IDL.Text,
          'preferredDate' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'submitSalonBooking' : IDL.Func(
      [
        IDL.Record({
          'service' : IDL.Text,
          'clientName' : IDL.Text,
          'appointmentDate' : IDL.Text,
          'appointmentTime' : IDL.Text,
          'notes' : IDL.Text,
          'clientPhone' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateClothingItem' : IDL.Func([ClothingItem], [], []),
  'updateSalonBookingStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClothingItem = IDL.Record({
    'id' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Variant({
      'accessories' : IDL.Null,
      'dresses' : IDL.Null,
      'tops' : IDL.Null,
      'bottoms' : IDL.Null,
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CryptoPayment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'coin' : IDL.Text,
    'createdAt' : IDL.Int,
    'txId' : IDL.Text,
    'user' : IDL.Principal,
  });
  const DentalBooking = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SalonBooking = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'appointmentDate' : IDL.Text,
    'appointmentTime' : IDL.Text,
    'notes' : IDL.Text,
    'clientPhone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateSubscription' : IDL.Func([], [], []),
    'addClothingItem' : IDL.Func([ClothingItem], [IDL.Nat], []),
    'approveCryptoPayment' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateSubscription' : IDL.Func([], [], []),
    'deleteClothingItem' : IDL.Func([IDL.Nat], [], []),
    'deleteDentalBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteSalonBooking' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClothingCatalog' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
    'getCryptoPendingPayments' : IDL.Func(
        [],
        [IDL.Vec(CryptoPayment)],
        ['query'],
      ),
    'getDentalBookings' : IDL.Func([], [IDL.Vec(DentalBooking)], ['query']),
    'getItemsByCategory' : IDL.Func(
        [
          IDL.Variant({
            'accessories' : IDL.Null,
            'dresses' : IDL.Null,
            'tops' : IDL.Null,
            'bottoms' : IDL.Null,
          }),
        ],
        [IDL.Vec(ClothingItem)],
        ['query'],
      ),
    'getMyPaymentStatus' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Variant({
              'pending' : IDL.Null,
              'approved' : IDL.Null,
              'rejected' : IDL.Null,
            })
          ),
        ],
        ['query'],
      ),
    'getSalonBookings' : IDL.Func([], [IDL.Vec(SalonBooking)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTryOnCountToday' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
    'recordTryOn' : IDL.Func([], [], []),
    'rejectCryptoPayment' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitCryptoPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'submitDentalBooking' : IDL.Func(
        [
          IDL.Record({
            'service' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'preferredDate' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'submitSalonBooking' : IDL.Func(
        [
          IDL.Record({
            'service' : IDL.Text,
            'clientName' : IDL.Text,
            'appointmentDate' : IDL.Text,
            'appointmentTime' : IDL.Text,
            'notes' : IDL.Text,
            'clientPhone' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateClothingItem' : IDL.Func([ClothingItem], [], []),
    'updateSalonBookingStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };